[package]
name = "giulia-lexer"
version = "0.1.0"
edition = "2021"
description = "Lexer for the CRL language (Giulia project, Phase 1)"
authors = ["Rafael Miotte <dev.miotte@gmail.com>"]
repository = "https://github.com/Miott0/Giulia"
license = "MIT"

[dependencies]
logos = { workspace = true }
thiserror = { workspace = true }
miette = { workspace = true }
